---
sidebar: sidebar 
permalink: concept_api_before_browser.html 
keywords: rest api, deploy rest api, rest, access browser, before you begin 
summary: Il y a plusieurs choses que vous devez savoir avant d’utiliser la page de documentation en ligne Deploy. 
---
= Avant d'accéder à l'API ONTAP Select Deploy avec un navigateur
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Il y a plusieurs choses que vous devez savoir avant d’utiliser la page de documentation en ligne Deploy.



== Plan de déploiement

Si vous prévoyez d'émettre des appels d'API dans le cadre de tâches de déploiement ou d'administration spécifiques, pensez à créer un plan de déploiement. Ce plan peut être formel ou informel et contient généralement vos objectifs et les appels d'API à utiliser. Pour plus d'informations, consultez la section Processus de workflow utilisant l'API REST Déployer.



== Exemples JSON et définitions de paramètres

Chaque appel d'API est décrit dans la page de documentation selon un format cohérent. Le contenu comprend des notes d'implémentation, des paramètres de requête et des codes d'état HTTP. De plus, vous pouvez afficher des détails sur le JSON utilisé avec les requêtes et réponses d'API comme suit :

* Exemple de valeur : si vous cliquez sur « Exemple de valeur » lors d'un appel d'API, une structure JSON typique s'affiche. Vous pouvez modifier l'exemple selon vos besoins et l'utiliser comme entrée pour votre requête.
* Modèle Si vous cliquez sur _Modèle_, une liste complète des paramètres JSON s'affiche, avec une description pour chaque paramètre.




== Attention lors de l'émission d'appels API

Toutes les opérations API effectuées via la page de documentation « Déployer » sont des opérations en direct. Veillez à ne pas créer, mettre à jour ou supprimer par erreur des configurations ou d'autres données.
