---
sidebar: sidebar 
permalink: concept_lic_cp_benefits.html 
keywords: license, licensing, Capacity Pools, benefits 
summary: L’utilisation du modèle de licence Capacity Pools au lieu du modèle de licence Capacity Tiers présente plusieurs avantages. 
---
= Résumé des avantages des licences ONTAP Select Capacity Pools
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
L’utilisation du modèle de licence Capacity Pools au lieu du modèle de licence Capacity Tiers présente plusieurs avantages.



== Utilisation plus efficace de la capacité de stockage

Avec les licences à niveaux de capacité, vous allouez une capacité de stockage fixe à chaque nœud. Tout espace inutilisé ne peut être partagé avec les autres nœuds et est gaspillé. Avec les licences à pools de capacité, chaque nœud consomme uniquement la capacité dont il a besoin, en fonction de la taille des agrégats de données.

Et comme la capacité est ancrée dans un pool central, elle peut être partagée entre de nombreux nœuds de votre organisation.



== Des frais administratifs considérablement réduits, ce qui se traduit par une baisse des coûts

Si vous utilisez des licences à plusieurs niveaux de capacité, vous devez obtenir et installer une licence pour chaque nœud. Avec les pools de capacité, une licence est attribuée à chaque pool partagé. Cela permet de réduire considérablement les frais administratifs et les coûts.



== Amélioration des mesures d'utilisation

L'interface utilisateur Web de déploiement fournit des informations d'utilisation améliorées pour les pools de capacité. Vous pouvez rapidement déterminer la quantité de stockage utilisée et disponible dans un pool de capacité, les nœuds qui utilisent le stockage d'un pool et les pools à partir desquels un cluster alloue de la capacité.
