---
sidebar: sidebar 
permalink: concept_usecase_overview.html 
keywords: ontap select, business use case overview, deployment, storage, development and testing 
summary: 'ONTAP Select convient à plusieurs types d"applications différents en fonction de la flexibilité inhérente fournie par la virtualisation de l"hyperviseur.' 
---
= ONTAP Select les besoins métier et les scénarios d'utilisation
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select convient à plusieurs types d'applications différents en fonction de la flexibilité inhérente fournie par la virtualisation de l'hyperviseur.



== Déploiement

À un niveau élevé, vous pouvez déployer ONTAP Select de deux manières différentes en fonction de la charge de travail sur les serveurs hôtes de l'hyperviseur.



=== Déploiement dédié

Avec le modèle de déploiement dédié, une seule instance d' ONTAP Select s'exécute sur le serveur hôte. Aucun autre traitement significatif n'est exécuté sur le même hôte hyperviseur.



=== Déploiement colocalisé

Avec le modèle de déploiement colocalisé, ONTAP Select partage l'hôte avec d'autres charges de travail. Plus précisément, des machines virtuelles supplémentaires exécutent généralement des applications de calcul. Ces charges de calcul sont locales au cluster ONTAP Select . Ce modèle prend en charge des exigences spécifiques en matière d'applications et de déploiement. Comme avec le modèle de déploiement dédié, chaque machine virtuelle ONTAP Select doit s'exécuter sur un hôte hyperviseur distinct et dédié.



== Stockage

ONTAP Select peut être utilisé comme stockage principal ou secondaire, selon les besoins de votre entreprise.



=== Stockage primaire

Dans certains cas, vous pouvez choisir de déployer ONTAP Select comme plateforme de stockage principale. Ces types d'implémentation varient et dépendent des caractéristiques de la charge de travail des applications ainsi que de vos objectifs métier.



=== Reprise après sinistre et stockage secondaire

Vous pouvez utiliser ONTAP Select pour implémenter un stockage supplémentaire qui renforce vos capacités de stockage principal. Ce stockage supplémentaire peut être utilisé pour soutenir les efforts de reprise après sinistre et les plans de sauvegarde des données de votre organisation.



== Développement et tests

Lors du déploiement de diverses applications au sein de votre organisation, vous pouvez utiliser ONTAP Select comme partie intégrante du processus global de développement et de test des applications. Par exemple, vous pourriez avoir besoin d'un stockage temporaire pour stocker les données d'entrée ou de sortie des tests. La durée de ces types de déploiements peut varier en fonction des caractéristiques et des exigences de l'application.
