---
sidebar: sidebar 
permalink: concept_lic_platforms.html 
keywords: license, licensing, platform license offerings, license offerings, standard, premium, premium xl 
summary: 'Vous pouvez acheter une licence ONTAP Select Capacity Tier ou Capacity Pool dans l"un des trois niveaux de capacité de la plateforme. Ces licences déterminent les capacités des hôtes sur lesquels vous déployez ONTAP Select.' 
---
= Découvrez les offres de licences de plateforme pour ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez acheter une licence ONTAP Select Capacity Tier ou Capacity Pool aux niveaux Standard, Premium ou Premium XL. Ces licences déterminent les capacités des hôtes sur lesquels vous déployez ONTAP Select.



== Ce que propose une offre de licence de plateforme

Une offre de licence spécifique détermine les capacités de l'hôte hyperviseur dans deux domaines :

* Type d'instance (CPU, mémoire)
* Fonctionnalités supplémentaires


Les offres de licences sont classées par ordre croissant de fonctionnalités, de Standard à Premium XL. En général, l'option de licence choisie vous donne accès aux fonctionnalités de ce niveau et de tous les niveaux inférieurs. Par exemple, le niveau Premium offre les fonctionnalités des niveaux Premium et Standard.

Le tableau suivant compare les fonctionnalités des licences standard, premium et premium XL.

[cols="25,25,25,25,25"]
|===
2+| La licence prend en charge... | Standard | Prime | Premium XL 


2+| Type d'instance | Petit seulement | Petit ou moyen | Petit, moyen ou grand 


.2+| Disques durs (HDD) dans un ... | Configuration RAID matérielle | Oui | Oui | Oui 


| configuration vNAS | Oui | Oui | Oui 


.3+| Disques SSD (Solid State Drives) dans un ... | Configuration RAID matérielle | Non | Oui | Oui 


| Configuration RAID logicielle | Non | Oui | Oui 


| configuration vNAS | Oui | Oui | Oui 


.3+| Les disques NVMe dans un ... | Configuration RAID matérielle | Non | Non | Oui 


| Configuration RAID logicielle | Non | Non | Oui 


| configuration vNAS | Oui | Oui | Oui 


2+| SDS MetroCluster | Non | Oui | Oui 
|===

NOTE: Les machines virtuelles basées sur le noyau (KVM) ne prennent pas en charge le type d'instance large.



== Comparer le support matériel pour les offres de licences de plateforme

Les licences Standard, Premium et Premium XL prennent en charge une large gamme de matériels et de logiciels. Pour obtenir des informations à jour sur les versions matérielles et logicielles, consultez lelink:https://mysupport.netapp.com/matrix/["Outil de matrice d'interopérabilité"^] .

[role="tabbed-block"]
====
.Élément de base
--
[cols="5"30"]
|===


2+| Type d'élément principal 3+| Description 


2+| Protocoles hôtes 3+| NFS, SMB/CIFS, iSCSI et NVMe sur TCP 


2+| Options de déploiement 3+| Nœud unique Cluster à deux nœuds (paire HA) Cluster à quatre, six ou huit nœuds 


2+| Capacité prise en charge (par nœud) 3+| Jusqu'à 400 To de données brutes (ESXi et KVM) 
|===
--
.Matériel
--
[cols="5"30"]
|===


2+| Type de matériel 3+| Description 


2+| Taille de l'instance | Petit | Moyen | Grand 


2+| Famille de processeurs | Intel Xeon E5-26xx v3 (Haswell) ou version ultérieure | Intel Xeon E5-26xx v3 (Haswell) ou version ultérieure | Intel Xeon E5-26xx v3 (Haswell) ou version ultérieure 


2+| ONTAP Select CPU / mémoire | 4 CPU virtuels (vCPU) / 16 Go de RAM | 8 vCPU / 64 Go de RAM | 16 vCPU / 128 Go de RAM 


2+| Configuration minimale requise pour le processeur et la mémoire de l'hôte ^1^ | 6 cœurs / 24 Go de RAM | 10 cœurs / 72 Go de RAM | 18 cœurs / 136 Go de RAM 


2+| Réseau (par nœud) 3+| Minimum de deux ports 1 GbE pour un cluster à nœud unique Minimum de quatre ports 1 GbE pour un cluster à deux nœuds (paire HA) Minimum de deux ports 10 GbE pour un cluster à quatre, six ou huit nœuds 
|===
^1^ Suppose deux cœurs et 8 Go de RAM pour l'hyperviseur.

--
.Type de stockage
--
Le tableau suivant fournit le type de licence minimum requis pour le stockage spécifié. 

[cols="5"30"]
|===


2+| Type de stockage 3+| Description 


2+| Type de licence | Standard | Prime | Premium XL 


2+| Taille de l'instance | Petit | Petites et moyennes | Petit, moyen et grand 


2+| DAS local avec contrôleur RAID matériel | 8 à 60 disques | 8 à 60 disques | 8 à 60 disques 


2+| Disque dur (SAS, NL-SAS, SATA) | Non Concerné | 4 à 60 disques | 4 à 60 disques 


2+| SSD (SAS) | Non Concerné | 4 à 60 disques (SSD uniquement) | 4 à 60 disques (SSD uniquement) 


2+| DAS local avec RAID logiciel | Non Concerné | En vigueur | 4 à 14 disques (NVMe uniquement) 


2+| Tableaux externes ^1^ 3+| Les banques de données hébergées sur des baies externes sont connectées via FC, FCoE, iSCSI et NFS (NFS n'est pas pris en charge pour KVM). Ces banques de données offrent une haute disponibilité et une résilience optimale. 
|===
^1^ La prise en charge du protocole de matrice externe reflète la connectivité de stockage en réseau.

--
.Logiciels
--
[cols="5"30"]
|===


2+| Type de logiciel 3+| Description 


2+| Prise en charge de l'hyperviseur (VMware) 3+| VMware vSphere 9.0, VMware vSphere 8.0GA et mises à jour 1 à 3, VMware vSphere 7.0GA et mises à jour 1 à 3C 


2+| Prise en charge de l'hyperviseur (KVM)  a| 
Red Hat Enterprise Linux (RHEL) 64 bits (KVM) 10.0, 9.6, 9.5, 9.4, 9.3, 9.2, 9.1, 9.0, 8.8, 8.7 et 8.6

Rocky Linux (KVM) 10.0, 9.6, 9.5, 9.4, 9.3, 9.2, 9.1, 9.0, 8.9, 8.8, 8.7 et 8.6

*Remarque* : Il existe des limitations de flux de travail RAID logiciel pour les hyperviseurs KVM sur les hôtes RHEL 10.0 et Rocky Linux 10.0. Pour plus d'informations, consultez les articles suivants de la base de connaissances :

* link:https://kb.netapp.com/on-prem/ontap/ontap-select/Select-Issues/CDEPLOY-4020["CDEPLOY-4020 : ONTAP Select Deploy : Message d’avertissement lors de la création du cluster HWR sous RHEL 10 et ROCKY 10"^]
* link:https://kb.netapp.com/on-prem/ontap/ontap-select/Select-Issues/CDEPLOY-4025["CDEPLOY-4025 : ONTAP Select DeployGUI : Les pools de stockage et les disques de stockage ne sont pas visibles pour SWR sur la page de création de cluster sur les hôtes RHEL10/Rocky 10"^]




2+| Logiciel de gestion 3+| Suite de gestion NetApp Active IQ Unified Manager ONTAP Select Deploy Utility SnapCenter (facultatif) 
|===
--
====
.Informations connexes
* link:concept_lic_production.html["En savoir plus sur les types de licences Capacity Tier et Capacity Pool"]

