---
sidebar: sidebar 
permalink: concept_ots_deploy.html 
keywords: ontap select deploy, deploy administration utility, deploy utility, functionality, accessing 
summary: 'ONTAP Select Deploy est l"utilitaire d"administration permettant de déployer et de gérer les clusters ONTAP Select .' 
---
= Déploiement de ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select Deploy est l'utilitaire d'administration permettant de déployer et de gérer les clusters ONTAP Select . Deploy est fourni sous forme de machine virtuelle Linux, à installer avant de créer un cluster ONTAP Select .



== Fonctionnalités de base

L'utilitaire d'administration Deploy exécute les fonctions principales suivantes :

* Enregistrez les détails de chaque hôte hyperviseur sur lequel ONTAP Select est déployé
* Configurer les hôtes et installer les licences requises
* Déployer et gérer les clusters ONTAP Select
* Maintenir un inventaire des clusters et des hôtes ONTAP Select
* Collecter et envoyer les données AutoSupport à NetApp
* Maintenir un ensemble interne d'images de nœuds ONTAP Select
* Prend en charge les formats de commande et les protocoles spécifiques à l'hyperviseur




== Façons d'accéder à l'utilitaire de déploiement

Plusieurs options s'offrent à vous pour accéder à l'utilitaire d'administration Deploy. Toutes les interfaces externes sont fonctionnellement équivalentes. Sélectionnez l'option d'accès la mieux adaptée à vos objectifs et exigences de déploiement. Dans tous les cas, vous devez vous connecter avec le compte administrateur et un mot de passe valide.



=== Interface utilisateur graphique Web

Vous pouvez accéder à l'utilitaire Deploy via un navigateur web moderne. L'interface Web fournit une interface intuitive et facile à utiliser et, dans la plupart des cas, sera votre interface principale lors de l'utilisation de l'utilitaire.



=== Interface de ligne de commande

Une interface de ligne de commande textuelle est disponible via l'interpréteur de commandes. Vous pouvez y accéder de plusieurs manières :

* Shell sécurisé (SSH)
* Console de machine virtuelle


La console de la machine virtuelle est généralement utilisée lors de l'installation et de la configuration initiale. Cependant, dans la plupart des cas, SSH offre une option plus flexible et plus pratique.



=== API de services Web REST

L'API des services Web REST, accessible aux clients externes, offre une autre option de connexion à l'utilitaire Deploy. Vous pouvez accéder à l'API via n'importe quel langage ou outil de programmation courant prenant en charge les services Web REST. Parmi les options les plus courantes, on trouve :

* Python
* Java
* Boucle


L’utilisation d’un langage de programmation ou de script offre la possibilité d’automatiser le déploiement et la gestion des clusters ONTAP Select .



=== Page Web de documentation en ligne ONTAP Select

L'affichage de la page de documentation en ligne dans l'utilitaire de déploiement constitue une autre façon d'accéder à l'API des services Web REST. Cependant, au lieu d'utiliser un langage de programmation, l'accès à l'API de gestion se fait via la page, via un navigateur. Les fonctionnalités suivantes sont disponibles :

* Une description détaillée de chaque appel dans l'API des services Web REST
* La possibilité d'émettre manuellement n'importe lequel des appels d'API


Vous pouvez accéder à la page de documentation en ligne en utilisant l'adresse IP ou le nom de domaine de la machine virtuelle Deploy. Pour afficher la page, saisissez une URL au format suivant dans votre navigateur (en remplaçant l'adresse IP ou le nom de domaine approprié par celui de votre instance de machine virtuelle Deploy) : `\http://<ip_address>/api/ui`
