---
sidebar: sidebar 
permalink: concept_terminology.html 
keywords: terminology, key concepts, concepts 
summary: Lorsque vous commencez à explorer ONTAP Select et à planifier un déploiement, il est utile de vous familiariser d’abord avec la terminologie et les concepts clés. 
---
= Terminologie et concepts clés ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Lorsque vous commencez à explorer ONTAP Select et à planifier un déploiement, il est utile de vous familiariser d’abord avec la terminologie et les concepts clés.

Déploiement de ONTAP Select:: ONTAP Select Deploy est l'utilitaire d'administration permettant de déployer des clusters ONTAP Select . Il s'exécute sur une machine virtuelle Linux dédiée. Vous pouvez y accéder via l'interface utilisateur Web, l'interface de gestion CLI et l'API REST.
Machine virtuelle basée sur le noyau:: La machine virtuelle basée sur le noyau (KVM) est une fonctionnalité de virtualisation du noyau Linux, qui lui permet d'agir comme une plateforme d'hyperviseur. Elle prend en charge une large gamme de systèmes d'exploitation invités.
Hôte hyperviseur par rapport au nœud ONTAP Select:: Un hôte hyperviseur est la plateforme matérielle principale qui héberge une machine virtuelle ONTAP Select . Lorsqu'une machine virtuelle ONTAP Select est déployée et active sur un hôte hyperviseur, elle est considérée comme un nœud ONTAP Select.
Cluster de ONTAP Select:: Vous pouvez créer un cluster ONTAP Select composé d'un, deux, quatre, six ou huit nœuds. Les clusters multi-nœuds contiennent toujours une ou plusieurs paires HA. Par exemple, un cluster à quatre nœuds est composé de deux paires HA. Un cluster à nœud unique ne fournit pas de fonctionnalité HA.
Préparation de l'environnement hôte de l'hyperviseur:: Avant d'utiliser l'utilitaire d'administration Deploy pour déployer un cluster ONTAP Select , vous devez préparer les hôtes hyperviseurs sur lesquels ONTAP Select sera exécuté, y compris les environnements de stockage et de réseau. Cette préconfiguration des hôtes est effectuée en dehors du produit ONTAP Select, en fonction des exigences et des limitations actuelles.
Évaluation versus déploiements de production:: Chaque nœud ONTAP Select fonctionne avec une licence d'évaluation ou une licence achetée. Une licence d'évaluation vous permet d'évaluer ONTAP Select avant de le déployer en production. Elle est générée et appliquée automatiquement. Si vous déployez un cluster en production, vous devez acheter une licence, ce qui implique de choisir :
+
--
* Modèle de licence
* Capacité de stockage
* Offre de licence de plateforme


--
Modèle de licence à niveaux de capacité:: Le modèle de licence par niveaux de capacité est l'option d'origine pour l'attribution de licences de stockage pour un déploiement ONTAP Select . Il est basé sur le modèle ONTAP utilisé avec NetApp AFF et FAS. Une licence distincte est requise pour chaque nœud. La capacité de stockage est verrouillée sur le nœud et perpétuelle (aucun renouvellement requis).
Modèle de licence des pools de capacité:: Le modèle de licence des pools de capacité a été introduit avec ONTAP Select 9.5 et Deploy 2.10. Une licence distincte est requise pour chaque pool de capacité de stockage. La licence du pool de capacité est liée à une instance de License Manager (c'est-à-dire une instance Deploy) et doit être renouvelée conformément aux conditions d'achat. Vous pouvez utiliser autant de pools de capacité que vous le souhaitez dans votre organisation. Cependant, comme les pools de capacité sont partagés par les nœuds ONTAP Select , le nombre de licences nécessaires est généralement inférieur à celui des licences par niveaux de capacité.
Gestionnaire de licences:: Le gestionnaire de licences est un composant logiciel prenant en charge les licences Capacity Pools. Il fait actuellement partie de l'utilitaire d'administration Deploy. LM loue du stockage aux nœuds ONTAP Select à partir des pools partagés qu'il gère. L'ID de verrouillage de licence est une chaîne numérique identifiant de manière unique chaque instance LM, et donc chaque instance Deploy. Vous devez utiliser à la fois le numéro de série et le LLID de la licence Capacity Pool pour générer un fichier de licence.
Offres de licences de plateforme:: Il existe trois offres de licence disponibles qui déterminent les capacités de taille de la machine virtuelle ONTAP Select lorsque vous achetez une licence :
+
--
* Standard
* Prime
* Premium XL


--


Pour plus d'informations, consultez les deux sections _Plan_ et _Licence_.

Pools de stockage versus magasins de données:: Un pool de stockage ONTAP Select est un conteneur de données logique conçu pour abstraire et masquer le stockage physique sous-jacent. Un pool de stockage est indépendant de l'hyperviseur. Déployé sur un hôte hyperviseur ESXi, le pool de stockage ONTAP Select est synonyme de la banque de données VMware.
MTU de cluster:: Le MTU du cluster est une fonctionnalité permettant de configurer la taille du MTU utilisé sur le réseau interne d'un cluster multi-nœuds ONTAP Select . L'utilitaire d'administration Deploy ajuste la taille du MTU lors de la configuration des paires HA pour s'adapter à votre environnement réseau. Vous pouvez également définir cette valeur manuellement.
ONTAP Select vNAS:: La solution ONTAP Select vNAS permet à un nœud ONTAP Select d'accéder aux banques de données VMware sur un stockage externe. Avec ONTAP Select vNAS, un contrôleur RAID local n'est plus nécessaire ; la fonctionnalité RAID est assurée par le stockage distant. ONTAP Select vNAS peut être configuré de la manière suivante :
+
--
* VMware vSAN
* Baie de stockage externe générique


--


Dans les deux cas, le stockage externe doit être configuré avant de créer un cluster ONTAP Select ou d'étendre la capacité de stockage d'un nœud existant.

Réhébergement de nœuds sur la machine virtuelle ESXi:: Lorsque vous déployez un cluster qui utilise un stockage externe disponible via la solution vNAS ONTAP Select (VMware vSAN ou une baie de stockage externe générique), la machine virtuelle ESXi hébergeant le nœud ONTAP Select peut être déplacée via des actions utilisant les fonctionnalités VMware suivantes :
+
--
* vMotion
* Haute disponibilité (HA)
* Planificateur de ressources distribuées (DRS)
+
L'utilitaire ONTAP Select Deploy détecte le mouvement de la machine virtuelle dans le cadre de l'exécution d'une opération sur le cluster, telle que :

* cluster en ligne
* cluster hors ligne
* stockage ajouté
+
Lorsqu'une machine virtuelle est déplacée, l'utilitaire Deploy met à jour sa base de données interne et configure le nouvel hôte ESXi. Toutes les actions effectuées sur le nœud ONTAP Select sont bloquées jusqu'à la fin du déplacement de la machine virtuelle et des mises à jour Deploy.



--
Open vSwitch pour KVM:: Open vSwitch (OVS) est une implémentation logicielle d'un commutateur virtuel prenant en charge plusieurs protocoles réseau. OVS est open source et disponible sous licence Apache 2.0.
Service de médiation:: L'utilitaire ONTAP Select Deploy inclut un service de médiation qui se connecte aux nœuds des clusters actifs à deux nœuds. Ce service surveille chaque paire HA et facilite la gestion des pannes.



CAUTION: Si vous disposez d'un ou plusieurs clusters à deux nœuds actifs, la machine virtuelle ONTAP Select Deploy qui administre les clusters doit être active en permanence. Si la machine virtuelle Deploy est arrêtée, le service de médiation est indisponible et la haute disponibilité est perdue pour les clusters à deux nœuds.

SDS MetroCluster:: MetroCluster SDS est une fonctionnalité qui offre une option de configuration supplémentaire lors du déploiement d'un cluster ONTAP Select à deux nœuds. Contrairement à un déploiement ROBO classique à deux nœuds, les nœuds MetroCluster SDS peuvent être séparés par une distance bien plus grande. Cette séparation physique permet des cas d'utilisation supplémentaires, comme la reprise après sinistre. Vous devez disposer d'une licence Premium ou supérieure pour utiliser MetroCluster SDS. De plus, le réseau entre les nœuds doit respecter une latence minimale.
Magasin d'informations d'identification:: Le magasin d'informations d'identification Deploy est une base de données sécurisée contenant les informations d'identification des comptes. Il sert principalement à enregistrer les hôtes de l'hyperviseur lors de la création d'un cluster. Consultez la section « Planification » pour plus d'informations.
Efficacité du stockage:: ONTAP Select offre des options d'efficacité de stockage similaires à celles des baies FAS et AFF . Conceptuellement, ONTAP Select avec SSD DAS (Direct-Attached Storage) (avec une licence premium) est similaire à une baie AFF . Les configurations utilisant DAS avec disques durs et toutes les configurations vNAS doivent être considérées comme similaires à une baie FAS . La principale différence entre les deux configurations réside dans la prise en charge par ONTAP Select avec SSD DAS de la déduplication agrégée en ligne et de la déduplication agrégée en arrière-plan. Les autres options d'efficacité de stockage sont disponibles pour les deux configurations.
+
--
Les configurations par défaut du vNAS activent une fonctionnalité d'optimisation de l'écriture appelée journalisation des données d'instance unique (SIDL). Avec ONTAP Select 9.6 et les versions ultérieures, les fonctionnalités d'optimisation du stockage ONTAP en arrière-plan sont activées avec SIDL activé. Consultez la section « Détails » pour plus d'informations.

--
Actualisation du cluster:: Après avoir créé un cluster, vous pouvez modifier sa configuration ou celle de la machine virtuelle en dehors de l'utilitaire Deploy, à l'aide ONTAP ou des outils d'administration de l'hyperviseur. Vous pouvez également migrer une machine virtuelle entraînant des modifications de configuration. Lorsque ces modifications se produisent, l'utilitaire Deploy n'est pas mis à jour automatiquement et peut se désynchroniser avec l'état du cluster. Vous pouvez utiliser la fonctionnalité d'actualisation du cluster pour mettre à jour la base de données de configuration de Deploy. L'actualisation du cluster est disponible via l'interface utilisateur Web de Deploy, l'interface de gestion CLI et l'API REST.
RAID logiciel:: Lors de l'utilisation d'un stockage à connexion directe (DAS), la fonctionnalité RAID est traditionnellement assurée par un contrôleur RAID matériel local. Vous pouvez également configurer un nœud pour utiliser le RAID logiciel, où le nœud ONTAP Select fournit la fonctionnalité RAID. Si vous utilisez le RAID logiciel, un contrôleur RAID matériel n'est plus nécessaire.


[[ontap-select-image-install]]
Installation de l'image ONTAP Select:: L'utilitaire d'administration Deploy ne contient qu'une seule version d' ONTAP Select. Cette version est la plus récente disponible au moment de la publication. La fonctionnalité d'installation d'image d' ONTAP Select vous permet d'ajouter des versions antérieures d' ONTAP Select à votre instance de l'utilitaire Deploy, qui peuvent ensuite être utilisées lors du déploiement d'un cluster ONTAP Select . Voirlink:task_cli_deploy_image_add.html["Ajouter ONTAP Select des images pour plus d'informations"] .



NOTE: Vous ne devez ajouter qu'une image ONTAP Select dont la version est antérieure à la version d'origine incluse avec votre instance de Deploy. L'ajout de versions ultérieures d' ONTAP Select sans mettre à jour Deploy n'est pas pris en charge.

Administration d'un cluster ONTAP Select après son déploiement:: Après avoir déployé un cluster ONTAP Select , vous pouvez le configurer comme un cluster ONTAP matériel. Par exemple, vous pouvez configurer un cluster ONTAP Select à l'aide de System Manager ou de l'interface de ligne de commande ONTAP standard.


.Informations connexes
link:task_cli_deploy_image_add.html["Ajouter une image ONTAP Select à déployer"]
