---
sidebar: sidebar 
permalink: concept_api_understanding_scripts.html 
keywords: rest api, deploy rest api, rest, python, python scripts, understanding 
summary: 'Les exemples de scripts Python vous permettent d"effectuer plusieurs tâches différentes. Il est important de bien comprendre ces scripts avant de les utiliser dans une instance Deploy en direct.' 
---
= Comprendre les scripts Python pour ONTAP Select Deploy
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les exemples de scripts Python vous permettent d'effectuer plusieurs tâches différentes. Il est important de bien comprendre ces scripts avant de les utiliser dans une instance Deploy en direct.



== Caractéristiques de conception communes

Les scripts ont été conçus avec les caractéristiques communes suivantes :

* Exécuter depuis l'interface de ligne de commande sur un ordinateur client. Vous pouvez exécuter les scripts Python depuis n'importe quel ordinateur client correctement configuré. Consultez _Avant de commencer_ pour plus d'informations.
* Accepter les paramètres d'entrée CLI Chaque script est contrôlé au niveau de la CLI via des paramètres d'entrée.
* Lire le fichier d'entrée Chaque script lit un fichier d'entrée en fonction de son objectif. Lors de la création ou de la suppression d'un cluster, vous devez fournir un fichier de configuration JSON. Lors de l'ajout d'une licence de nœud, vous devez fournir un fichier de licence valide.
* Utiliser un module de support commun. Le module de support commun _deploy_requests.py_ contient une seule classe. Il est importé et utilisé par chacun des scripts.




== Créer un cluster

Vous pouvez créer un cluster ONTAP Select à l'aide du script cluster.py. En fonction des paramètres de l'interface de ligne de commande et du contenu du fichier d'entrée JSON, vous pouvez adapter le script à votre environnement de déploiement comme suit :

* Hyperviseur : vous pouvez déployer sur ESXI ou KVM (selon la version de Deploy). Lors d'un déploiement sur ESXi, l'hyperviseur peut être géré par vCenter ou être un hôte autonome.
* Taille du cluster Vous pouvez déployer un cluster à nœud unique ou à nœuds multiples.
* Licence d'évaluation ou de production Vous pouvez déployer un cluster avec une licence d'évaluation ou achetée pour la production.


Les paramètres d’entrée CLI pour le script incluent :

* Nom d'hôte ou adresse IP du serveur de déploiement
* Mot de passe pour le compte utilisateur administrateur
* Nom du fichier de configuration JSON
* Indicateur détaillé pour la sortie du message




== Ajouter une licence de nœud

Si vous choisissez de déployer un cluster de production, vous devez ajouter une licence pour chaque nœud à l'aide du script _add_license.py_. Vous pouvez ajouter la licence avant ou après le déploiement du cluster.

Les paramètres d’entrée CLI pour le script incluent :

* Nom d'hôte ou adresse IP du serveur de déploiement
* Mot de passe pour le compte utilisateur administrateur
* Nom du fichier de licence
* Nom d'utilisateur ONTAP avec privilèges pour ajouter la licence
* Mot de passe pour l'utilisateur ONTAP




== Supprimer un cluster

Vous pouvez supprimer un cluster ONTAP Select existant à l'aide du script _delete_cluster.py_.

Les paramètres d’entrée CLI pour le script incluent :

* Nom d'hôte ou adresse IP du serveur de déploiement
* Mot de passe pour le compte utilisateur administrateur
* Nom du fichier de configuration JSON

