---
sidebar: sidebar 
permalink: concept_lic_cp_operation.html 
keywords: license, licensing, Capacity Pools, operation details 
summary: 'Le modèle de licence « Pools de capacité » diffère du modèle « Niveaux de capacité ». Au lieu d"une capacité de stockage dédiée à chaque nœud, celle-ci est allouée à un pool et partagée entre plusieurs nœuds. Des composants et processus supplémentaires ont été créés pour prendre en charge le modèle « Pools de capacité ».' 
---
= Détails opérationnels du modèle de licence ONTAP Select Capacity Pools
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le modèle de licence « Pools de capacité » diffère du modèle « Niveaux de capacité ». Au lieu d'une capacité de stockage dédiée à chaque nœud, celle-ci est allouée à un pool et partagée entre plusieurs nœuds. Des composants et processus supplémentaires ont été créés pour prendre en charge le modèle « Pools de capacité ».



== Gestionnaire de licences

Le gestionnaire de licences s'exécute comme un processus distinct dans chaque instance de l'utilitaire d'administration Deploy. Parmi les fonctionnalités offertes par LM, on trouve :

* Générer un numéro de série unique à vingt chiffres pour chaque nœud en fonction du numéro de série de la licence Capacity Pool
* Créer des baux pour la capacité des pools de capacité partagés en fonction des demandes des nœuds ONTAP Select
* Signaler les informations d'utilisation du pool via l'interface utilisateur de déploiement




== Caractéristiques du bail

L'espace de stockage alloué à chaque agrégat de données sur un nœud utilisant une licence de pool de capacité doit être associé à un bail. Le nœud demande un bail de stockage et, si la capacité est disponible, le gestionnaire de licences répond par un bail. Chaque bail possède les attributs explicites ou implicites suivants :

* Gestionnaire de licences Chaque nœud ONTAP Select est associé à une instance du gestionnaire de licences
* Pool de capacité Chaque nœud ONTAP Select est associé à un pool de capacité
* Allocation de stockage Une valeur de capacité spécifique est attribuée dans le bail
* Date et heure d'expiration Les baux ont une durée comprise entre une heure et sept jours selon la configuration de l'utilisateur.




== ID de verrouillage de licence

Chaque instance du Gestionnaire de licences, et donc chaque instance de l'utilitaire Deploy correspondante, est identifiée par un numéro unique de 128 bits. Ce numéro est combiné au numéro de série de la licence du pool de capacité à neuf chiffres pour verrouiller le pool sur une instance spécifique du Gestionnaire de licences (qui est en réalité une instance Deploy). Vous devez fournir ces deux valeurs sur le site de support NetApp lors de la génération du fichier de licence NetApp (NLF).

Vous pouvez déterminer l'ID de verrouillage de licence pour votre instance de déploiement à l'aide de l'interface utilisateur Web des manières suivantes :

* Page de démarrage : cette page s'affiche lors de votre première connexion à Deploy. Vous pouvez également l'afficher en cliquant sur le menu déroulant en haut à droite et en sélectionnant « Démarrage ». Le LLID s'affiche dans la section « Ajouter des licences ».
* Administration Cliquez sur l'onglet *Administration* en haut de la page, puis cliquez sur *Systèmes* et *Paramètres*.




== Opérations de location de base

Un nœud ONTAP Select doit localiser ou demander un bail de capacité valide à chaque création, extension ou modification d'un agrégat de données. Un bail obtenu lors d'une précédente requête encore valide peut être utilisé, ou un nouveau bail peut être demandé si nécessaire. Pour localiser un bail de pool de capacité, le nœud ONTAP Select suit les étapes suivantes :

. Si un bail existant est situé au niveau du nœud, il est utilisé tant que tous les éléments suivants sont vrais :
+
** Le bail n'a pas expiré
** La demande de stockage pour l'agrégat ne dépasse pas la capacité de location


. Si un bail existant ne peut pas être localisé, le nœud demande un nouveau bail au gestionnaire de licences.




== Renvoyer la capacité de stockage à un pool de capacités

La capacité de stockage est allouée à partir d'un pool de capacité selon les besoins, et chaque nouvelle requête peut réduire l'espace disponible dans le pool. La capacité de stockage est restituée au pool dans plusieurs situations, notamment :

* Le bail d'un agrégat de données expire et n'est pas renouvelé par le nœud
* L'agrégat de données est supprimé



NOTE: Si une machine virtuelle ONTAP Select est supprimée, tous les baux actifs restent en vigueur jusqu'à leur expiration. Dans ce cas, la capacité est restituée au pool.
