---
sidebar: sidebar 
permalink: concept_adm_upgrading_nodes.html 
keywords: administer, administering, web, upgrading nodes 
summary: 'Après avoir déployé un cluster ONTAP Select , vous pouvez mettre à niveau l"image ONTAP de chaque nœud selon vos besoins à l"aide de la procédure de mise à niveau logicielle ONTAP standard.' 
---
= Mettre à niveau les nœuds ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Après avoir déployé un cluster ONTAP Select , vous pouvez mettre à niveau l’image ONTAP sur chaque nœud du cluster selon vos besoins.


CAUTION: L'utilitaire d'administration Deploy ne permet pas de mettre à niveau des nœuds ONTAP Select existants. Il permet uniquement de créer de nouveaux clusters ONTAP Select .



== Procédure générale

À un niveau élevé, vous devez utiliser les étapes suivantes pour mettre à niveau un nœud ONTAP Select existant.

. Rendez-vous sur la page de téléchargements du site d'assistance NetApp.
+
https://mysupport.netapp.com/site/downloads["NetApp Support Téléchargements"^]

. Cliquez sur *ONTAP Select Node Upgrade*.
. Sélectionnez et téléchargez l'image de mise à niveau appropriée en répondant à toutes les invites si nécessaire.
+
Consultez les notes de version pour obtenir des informations supplémentaires et connaître les procédures requises avant de mettre à niveau un nœud ONTAP Select.

. Mettez à niveau le nœud ONTAP Select en suivant les procédures de mise à niveau ONTAP standard avec le fichier de mise à niveau ONTAP Select . Pour plus d'informations sur les chemins de mise à niveau pris en charge, consultez lelink:https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html["Chemins de mise à niveau ONTAP pris en charge"^] .




== Rétablir un nœud ONTAP Select

Il est impossible de restaurer une version antérieure à celle d'origine d'un nœud ONTAP Select . Par exemple:

ONTAP Select 9.16.1 est installé par défaut.:: Vous pouvez mettre à niveau le nœud vers la version 9.17.1, puis revenir à la version 9.16.1 si nécessaire.
ONTAP Select 9.17.1 est installé par défaut.:: Le retour à une version antérieure est impossible car aucune version précédente n'était installée.




== Utiliser le pilote réseau VMXNET3

VMXNET3 est le pilote réseau par défaut inclus dans les nouveaux déploiements de clusters sur VMware ESXi. Si vous mettez à niveau un nœud ONTAP Select existant exécutant ONTAP Select 9.4 ou une version antérieure, le pilote réseau n'est pas automatiquement mis à niveau. Vous devez effectuer la mise à niveau manuelle vers VMXNET3. Contactez le support NetApp pour obtenir de l'aide concernant la mise à niveau.

.Informations connexes
link:https://docs.netapp.com/us-en/ontap/upgrade/index.html["Présentation de la mise à niveau ONTAP"^]
