---
sidebar: sidebar 
permalink: reference_plan_dep_vmware.html 
keywords: plan, planning, ontap select deploy, vmware requirements 
summary: Il existe plusieurs exigences et restrictions spécifiques à l’environnement VMware que vous devez prendre en compte avant d’installer l’utilitaire ONTAP Select Deploy dans un environnement VMware. 
---
= Considérations relatives à l'hôte de l'hyperviseur ONTAP Select Deploy
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Il existe plusieurs problèmes de planification liés à l’hôte hyperviseur que vous devez prendre en compte.


CAUTION: Vous ne devez pas modifier directement la configuration d'une machine virtuelle ONTAP Select, sauf indication contraire du support NetApp . Une machine virtuelle ne doit être configurée et modifiée que via l'utilitaire d'administration Deploy. Toute modification apportée à une machine virtuelle ONTAP Select en dehors de l'utilitaire Deploy sans l'aide du support NetApp peut entraîner son échec et la rendre inutilisable.



== Indépendant de l'hyperviseur

Les utilitaires d’administration ONTAP Select et ONTAP Select Deploy sont tous deux indépendants de l’hyperviseur.

Les hyperviseurs suivants sont pris en charge pour l'administration ONTAP Select et d' ONTAP Select Deploy :

* VMware ESXi
* Machine virtuelle basée sur le noyau (KVM)



NOTE: Reportez-vous aux informations de planification et aux notes de publication spécifiques à l'hyperviseur pour plus de détails sur les plates-formes prises en charge.

.Hyperviseur pour ONTAP Select les nœuds et l'utilitaire d'administration
L'utilitaire d'administration Deploy et les nœuds ONTAP Select fonctionnent tous deux comme des machines virtuelles. L'hyperviseur choisi pour l'utilitaire Deploy est indépendant de celui choisi pour les nœuds ONTAP Select . Vous bénéficiez d'une flexibilité totale lors de l'association des deux :

* L'utilitaire de déploiement exécuté sur VMware ESXi peut créer et gérer des clusters ONTAP Select sur VMware ESXi ou KVM
* L'utilitaire de déploiement exécuté sur KVM peut créer et gérer des clusters ONTAP Select sur VMware ESXi ou KVM


.Une ou plusieurs instances du nœud ONTAP Select par hôte
Chaque nœud ONTAP Select fonctionne comme une machine virtuelle dédiée. Vous pouvez créer plusieurs nœuds sur le même hôte hyperviseur, avec les restrictions suivantes :

* Plusieurs nœuds d'un même cluster ONTAP Select ne peuvent pas s'exécuter sur le même hôte. Tous les nœuds d'un hôte spécifique doivent provenir de clusters ONTAP Select différents.
* Vous devez utiliser un stockage externe.
* Si vous utilisez un RAID logiciel, vous ne pouvez déployer qu'un seul nœud ONTAP Select sur l'hôte.


.Cohérence de l'hyperviseur pour les nœuds d'un cluster
Tous les hôtes d’un cluster ONTAP Select doivent s’exécuter sur la même version et la même version du logiciel hyperviseur.

.Nombre de ports physiques sur chaque hôte
Vous devez configurer chaque hôte pour utiliser un, deux ou quatre ports physiques. Bien que vous ayez une certaine flexibilité dans la configuration des ports réseau, suivez ces recommandations autant que possible :

* Un hôte dans un cluster à nœud unique doit avoir deux ports physiques.
* Chaque hôte d'un cluster multi-nœuds doit disposer de quatre ports physiques


.Intégrer ONTAP Select à un cluster matériel ONTAP
Vous ne pouvez pas ajouter un nœud ONTAP Select directement à un cluster matériel ONTAP . Cependant, vous pouvez éventuellement établir une relation d'appairage de cluster entre un cluster ONTAP Select et un cluster ONTAP matériel.



== Environnement d'hyperviseur VMware

Il existe plusieurs exigences et restrictions spécifiques à l’environnement VMware que vous devez prendre en compte avant d’installer l’utilitaire ONTAP Select Deploy dans un environnement VMware.

.Configuration matérielle requise pour le serveur hôte ESXi
Votre hôte hyperviseur ESXi doit respecter plusieurs exigences minimales en matière de ressources. Assurez-vous que les hôtes sur lesquels ONTAP Select est déployé répondent aux exigences de base suivantes :

* Serveur ESXi :
+
** Le matériel et les logiciels doivent être 64 bits
** Doit adhérer aux mêmes versions prises en charge que celles définies pour un nœud ONTAP Select


* CPU virtuels (2)
* Mémoire virtuelle (4 Go)
* Stockage (40 Go)
* DHCP activé (peut également attribuer une adresse IP statique)


.Connectivité réseau
Vous devez vous assurer que l'interface réseau de la machine virtuelle ONTAP Select Deploy est configurée et dispose d'une adresse IP de gestion unique. Vous pouvez utiliser DHCP pour attribuer dynamiquement une adresse IP ou configurer manuellement une adresse IP statique.

Selon vos choix de déploiement, la machine virtuelle Deploy doit pouvoir se connecter au serveur vCenter, aux hôtes hyperviseurs ESXi et aux nœuds ONTAP Select qu'elle gère. Vous devez configurer vos pare-feu pour autoriser le trafic requis.

Deploy utilise l'API VMware VIX pour communiquer avec le serveur vCenter et les hôtes ESXi. Initialement, une connexion est établie via SOAP sur SSL sur le port TCP 443. Ensuite, une connexion est établie via SSL sur le port 902. Deploy émet également des commandes PING pour vérifier la présence d'un hôte ESXi à l'adresse IP spécifiée.

Le déploiement doit également pouvoir communiquer avec les adresses IP de gestion du nœud et du cluster ONTAP Select à l'aide des protocoles suivants :

* Commande PING (ICMP)
* SSH (port 22)
* SSL (port 443)


.Prise en charge de la version IP 4
ONTAP Select Deploy prend uniquement en charge IP version 4 (IPv4). IP version 6 (IPv6) n'est pas prise en charge. Cette restriction affecte ONTAP Select des manières suivantes :

* Vous devez attribuer une adresse IPv4 au LIF de gestion de la machine virtuelle Deploy.
* Le déploiement ne peut pas créer de nœuds ONTAP Select configurés pour utiliser IPv6 sur les LIF ONTAP .




== Considérations relatives au déploiement du serveur VMware vCenter dans ONTAP Select



=== Privilèges VMware vSphere pour ESA

La liste suivante répertorie les privilèges spécifiques pour la bibliothèque de contenu vSphere dont vous avez besoin pour créer et gérer l'architecture de stockage vSAN Express (ESA) dans vCenter :

* Ajouter un élément de bibliothèque
* Créer une bibliothèque locale
* Supprimer un élément de la bibliothèque
* Supprimer la bibliothèque locale
* Stockage de lecture
* Mettre à jour les fichiers
* Mettre à jour la bibliothèque
* Mettre à jour l'élément de la bibliothèque
* Mettre à jour la bibliothèque locale

