---
sidebar: sidebar 
permalink: reference_host_modify_command.html 
keywords: host modify, command, syntax, host management server 
summary: 'Vous pouvez utiliser la commande host modify pour modifier un serveur de gestion d"hôte avec cette instance d" ONTAP Select Deploy.' 
---
= Modifier un serveur de gestion d'hôte pour ONTAP Select Deploy
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez utiliser le `host modify` commande permettant de modifier un serveur de gestion d'hôte avec cette instance d' ONTAP Select Deploy.



== Syntaxe

`host modify [-help] [-foreground] -name _name_ -mgmt-server _management_server_ [-username _username_]`



== Paramètres requis

[cols="35,65"]
|===


| Paramètre | Description 


 a| 
`-name _name_`
 a| 
L'adresse IP ou le FQDN de l'hôte que vous souhaitez modifier.



 a| 
`-mgmt-server _management_server_`
 a| 
L'adresse IP ou le nom de domaine complet (FQDN) du serveur de gestion hôte à définir sur l'hôte. Spécifiez « - » (trait d'union) pour dissocier le serveur de gestion de l'hôte. Les informations d'identification de ce serveur de gestion doivent être ajoutées avant l'enregistrement de cet hôte. `credential add` commande.

|===


== Paramètres facultatifs

[cols="35,65"]
|===


| Paramètre | Description 


 a| 
`-help`
 a| 
Affiche le message d'aide.



 a| 
`-foreground`
 a| 
Ce paramètre contrôle le comportement des commandes de longue durée. S'il est défini, la commande s'exécute au premier plan et les messages d'événement liés à l'opération s'affichent au fur et à mesure.



 a| 
`-username _username_`
 a| 
Nom d'utilisateur donnant accès à cet hôte. Ce champ est requis uniquement si l'hôte n'est pas géré par un serveur de gestion (c'est-à-dire un hôte ESX géré par un vCenter).

|===