---
sidebar: sidebar 
permalink: task_lic_acquire_ct.html 
keywords: license, licensing, acquire, Capacity Tiers 
summary: Lorsque vous utilisez des licences par niveaux de capacité, vous devez acquérir un fichier de licence pour chaque nœud ONTAP Select . Ce fichier de licence définit la capacité de stockage du nœud et est verrouillé sur celui-ci via le numéro de série unique à neuf chiffres attribué par NetApp. 
---
= Acquérir une licence ONTAP Select Capacity Tier
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Lorsque vous utilisez des licences par niveaux de capacité, vous devez acquérir un fichier de licence pour chaque nœud ONTAP Select . Ce fichier de licence définit la capacité de stockage du nœud et est verrouillé sur celui-ci via le numéro de série unique à neuf chiffres attribué par NetApp.

.Avant de commencer
Vous devez disposer du numéro de série de licence à neuf chiffres attribué au nœud par NetApp. Avant d'acquérir un fichier de licence, veuillez patienter au moins vingt-quatre heures après la date d'expédition de votre commande.

.À propos de cette tâche
Vous devez effectuer cette tâche pour chaque nœud ONTAP Select nécessitant une licence Capacity Tier.

.Étapes
. Accédez au site de licence ONTAP Select à l'aide d'un navigateur Web :
+
`https://register.netapp.com/register/getlicensefile`

. Sign in à l’aide des informations d’identification de votre compte NetApp .
. Sur la page *Générateur de licence*, sélectionnez l'offre de licence souhaitée dans la liste déroulante.
. Remplissez les champs restants sur la même page, y compris le *Numéro de série du produit*, qui est le numéro de série du nœud ONTAP Select .
. Cliquez sur *Soumettre*.
. Une fois la demande validée, sélectionnez le mode de livraison de la licence.
+
Vous pouvez cliquer sur *Télécharger la licence* ou *Envoyer la licence par e-mail*.

. Confirmez que vous avez reçu le fichier de licence en fonction de la méthode de livraison sélectionnée.


.Après avoir terminé
Vous devez télécharger le fichier de licence dans l'utilitaire d'administration Deploy avant de pouvoir l'appliquer à un nœud ONTAP Select .
