---
sidebar: sidebar 
permalink: task_adm_resize.html 
keywords: administer, administering, web, resizing nodes, resizing 
summary: Après avoir déployé un cluster ONTAP Select , vous pouvez mettre à niveau le type d’instance d’hyperviseur des nœuds à l’aide de l’utilitaire d’administration Déployer. 
---
= Redimensionner les nœuds du cluster ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Après avoir déployé un cluster ONTAP Select , vous pouvez mettre à niveau le type d’instance d’hyperviseur des nœuds à l’aide de l’utilitaire d’administration Déployer.


NOTE: Vous pouvez effectuer l'opération de redimensionnement des nœuds de cluster lorsque vous utilisez le modèle de licence Niveaux de capacité et le modèle de licence Pools de capacité.


NOTE: Le redimensionnement vers le type d’instance de grande taille n’est pris en charge que sur ESXi.

.Avant de commencer
Le cluster doit être dans l’état en ligne.

.À propos de cette tâche
Cette tâche décrit l'utilisation de l'interface utilisateur Web Deploy. Vous pouvez également utiliser l'interface de ligne de commande Deploy pour redimensionner l'instance. Quelle que soit l'interface utilisée, le temps nécessaire à l'opération de redimensionnement peut varier considérablement en fonction de plusieurs facteurs et peut être long. Vous ne pouvez redimensionner un nœud qu'à une taille supérieure.

.Étapes
. Sign in à l’interface utilisateur Web de l’utilitaire de déploiement à l’aide du compte administrateur.
. Cliquez sur l’onglet *Cluster* en haut de la page et sélectionnez le cluster souhaité dans la liste.
. Sur la page des détails du cluster, cliquez sur l’icône d’engrenage à droite de la page et sélectionnez *Redimensionnement de l’instance*.
. Sélectionnez le *Type d'instance* et fournissez les informations d'identification ONTAP , puis cliquez sur *Modifier*.


.Après avoir terminé
Vous devez attendre que l’opération de redimensionnement soit terminée.
