---
sidebar: sidebar 
permalink: task_cli_deploy_image_remove.html 
keywords: administer, administering, cli, deploy, ontap select image, remove 
summary: 'Vous pouvez supprimer les images ONTAP Select de votre instance de l"utilitaire d"administration Deploy lorsqu"elles ne sont plus nécessaires.' 
---
= Supprimer une image ONTAP Select du déploiement
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez supprimer les images ONTAP Select de votre instance de l'utilitaire d'administration Deploy lorsqu'elles ne sont plus nécessaires.


CAUTION: Vous ne devez supprimer aucune image ONTAP Select utilisée par un cluster.

.À propos de cette tâche
Vous pouvez supprimer les anciennes images ONTAP Select qui ne sont pas actuellement utilisées par un cluster ou dont l'utilisation est prévue avec un futur déploiement de cluster.

.Étapes
. Sign in à l'interface de ligne de commande de l'utilitaire de déploiement à l'aide de SSH avec le compte administrateur (admin).
. Affichez les clusters gérés par Deploy et enregistrez les images ONTAP en cours d'utilisation :
+
[source, cli]
----
cluster show
----
+
Notez le numéro de version et la plate-forme de l'hyperviseur dans chaque cas.

. Démarrez le shell Bash :
+
[source, cli]
----
shell bash
----
. Afficher toutes les images ONTAP Select disponibles :
+
[source, cli]
----
ls -lh /opt/netapp/images
----
. Supprimez éventuellement l’image ONTAP Select avec votre hôte hyperviseur.
+
[role="tabbed-block"]
====
.Exemple ESXi
--
[source, asciidoc]
----
rm -r /opt/netapp/images/DataONTAPv-9.3RC1-vidconsole-esx.ova
----
--
.Exemple KVM
--
[source, asciidoc]
----
rm -r /opt/netapp/images/DataONTAPv-9.3RC1-serialconsole-kvm.raw.tar
----
--
====

