---
sidebar: sidebar 
permalink: task_cli_connectivity.html 
keywords: administer, administering, cli, connectivity, network connectivity, network checker 
summary: 'Vous pouvez tester la connectivité réseau entre deux ou plusieurs nœuds ONTAP Select sur le réseau du cluster interne. Ce test est généralement exécuté avant le déploiement d"un cluster multi-nœuds afin de détecter les problèmes susceptibles d"entraîner l"échec de l"opération.' 
---
= Confirmer la connectivité réseau entre les nœuds ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez tester la connectivité réseau entre deux ou plusieurs nœuds ONTAP Select sur le réseau du cluster interne. Ce test est généralement exécuté avant le déploiement d'un cluster multi-nœuds afin de détecter les problèmes susceptibles d'entraîner l'échec de l'opération.

.Avant de commencer
Tous les nœuds ONTAP Select inclus dans le test doivent être configurés et sous tension.

.À propos de cette tâche
À chaque démarrage d'un test, une nouvelle exécution est créée en arrière-plan et un identifiant d'exécution unique lui est attribué. Une seule exécution peut être active à la fois.

Le test dispose de deux modes qui contrôlent son fonctionnement :

* Rapide : ce mode effectue un test de base non perturbateur. Un test PING est effectué, ainsi qu'un test de la taille MTU du réseau et du vSwitch.
* Étendu : ce mode effectue un test plus complet sur tous les chemins réseau redondants. Si vous l'exécutez sur un cluster ONTAP Select actif, ses performances peuvent être affectées.



NOTE: Il est recommandé de toujours effectuer un test rapide avant de créer un cluster multi-nœuds. Une fois le test rapide terminé, vous pouvez éventuellement effectuer un test étendu en fonction de vos besoins de production.

.Étapes
. Sign in à l’interface de ligne de commande de l’utilitaire de déploiement à l’aide du compte administrateur.
. Affichez les exécutions en cours du vérificateur de connectivité réseau et vérifiez qu'aucune exécution n'est active :
+
`network connectivity-check show`

. Démarrez le vérificateur de connectivité réseau et notez l'identifiant d'exécution dans la sortie de la commande :
+
`network connectivity-check start -host-names HOSTNAMES -vswitch-type VSWITCH_TYPE-mode MODE`

+
Exemple

+
[listing]
----
network connectivity-check start -host-names 10.234.81.14
10.234.81.15 -vswitch-type StandardVSwitch -mode quick
----
. Surveillez la progression du vérificateur de connectivité réseau en fonction de l'identifiant d'exécution :
+
`network connectivity-check show -run-id RUN_ID`



.Après avoir terminé
Le vérificateur de connectivité réseau effectue généralement le nettoyage en supprimant les ports et adresses IP temporaires ajoutés au groupe de ports internes ONTAP. Toutefois, si le vérificateur de connectivité ne parvient pas à supprimer les ports temporaires, vous devez effectuer un nettoyage manuel en réexécutant la commande CLI avec l'option correspondante. `-mode cleanup` . Si vous ne supprimez pas les ports temporaires du groupe de ports ONTAP-Internal, la machine virtuelle ONTAP Select risque de ne pas être créée avec succès.
