---
sidebar: sidebar 
permalink: task_cli_deploy_image_add.html 
keywords: administer, administering, cli, deploy, ontap select image, add 
summary: 'Ajoutez une image ONTAP Select à votre instance de l"utilitaire d"administration Deploy. Après l"installation, vous pouvez l"utiliser lors du déploiement d"un cluster ONTAP Select.' 
---
= Ajouter une image ONTAP Select à déployer
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Ajoutez une image ONTAP Select à votre instance de l'utilitaire d'administration Deploy. Une fois l'image installée, vous pouvez l'utiliser lors du déploiement d'un cluster ONTAP Select.

.Avant de commencer
Avant d’ajouter de nouvelles images ONTAP Select à déployer, vous devez d’abord supprimer toutes les images inutiles.


NOTE: Vous ne devez ajouter qu'une image ONTAP Select dont la version est antérieure à la version d'origine fournie avec votre instance de l'utilitaire Deploy. L'ajout de versions ultérieures d' ONTAP Select dès leur mise à disposition par NetApp n'est pas pris en charge.



== Étape 1 : Téléchargez l'image d'installation

Pour commencer le processus d'ajout d'une image ONTAP Select à une instance de l'utilitaire Deploy, vous devez télécharger l'image d'installation depuis le site de support NetApp . L'image d'installation ONTAP Select est formatée dans un fichier compressé unique.

.Étapes
. Accédez à la page link:https://mysupport.netapp.com/site/downloads/["NetApp Support Site téléchargements"^].
. Faites défiler vers le bas et sélectionnez *ONTAP Select Image*.
. Sélectionnez la version souhaitée de l'image d'installation.
. Consultez le contrat de licence utilisateur final (CLUF) et sélectionnez *Accepter et continuer*.
. Sélectionnez et téléchargez le package *ONTAP Select Image Install* approprié. Répondez à toutes les invites si nécessaire.




== Étape 2 : Télécharger l’image d’installation sur Deploy

Après avoir acquis l’image d’installation ONTAP Select , vous devez télécharger le fichier sur la machine virtuelle Deploy.

.Avant de commencer
Vérifiez que le fichier image d'installation est disponible sur votre poste de travail local. Vous devez également disposer du mot de passe du compte utilisateur administrateur Deploy.

.À propos de cette tâche
Cette tâche décrit une méthode de téléchargement du fichier sur la machine virtuelle Deploy. D'autres options peuvent être plus adaptées à votre environnement.

.Étape
. Dans une invite de commandes sur votre poste de travail local, téléchargez le fichier image sur la machine virtuelle Deploy, comme indiqué dans les exemples suivants :
+
....
scp image_v_93_install_esx.tgz admin@10.234.81.101:/home/admin (provide password when prompted)
....
+
....
sftp admin@10.234.81.101 (provide password when prompted)
put image_v_93_install_esx.tgz
exit
....


.Résultat
Le fichier d'installation du nœud est stocké dans le répertoire personnel de l'utilisateur administrateur.



== Étape 3 : Ajouter l'image d'installation

Ajoutez l'image d'installation ONTAP Select au répertoire des images de déploiement afin qu'elle soit disponible lors du déploiement d'un nouveau cluster.

.Avant de commencer
Vous devez connaître le répertoire dans lequel se trouve le fichier image d'installation sur la machine virtuelle de l'utilitaire de déploiement. Le fichier est supposé se trouver dans le répertoire personnel de l'administrateur.

.Étapes
. Sign in à l'interface de ligne de commande de l'utilitaire de déploiement à l'aide de SSH avec le compte administrateur (admin).
. Démarrez le shell Bash :
+
[source, cli]
----
shell bash
----
. Placez le fichier image d'installation dans le répertoire images, comme indiqué dans l'exemple suivant :
+
`tar -xf image_v_93_install_esx.tgz -C /opt/netapp/images/`





== Étape 4 : Afficher les images d’installation disponibles

Afficher les images ONTAP Select disponibles lors du déploiement d'un nouveau cluster.

.Étapes
. Accédez à la page Web de documentation en ligne sur la machine virtuelle de l'utilitaire de déploiement et connectez-vous à l'aide du compte administrateur (admin) :
+
`\http://<FQDN|IP_ADDRESS>/api/ui`

+
Utilisez le nom de domaine ou l’adresse IP de la machine virtuelle de déploiement.

. Accédez au bas de la page et sélectionnez *Déployer* puis *GET /images*.
. Sélectionnez *Essayez-le !* pour afficher les images ONTAP Select disponibles.
. Confirmez que l’image souhaitée est disponible.

