---
sidebar: sidebar 
permalink: task_cli_migrate_deploy.html 
keywords: administer, administering, cli, deploy, deploy instance, migrate 
summary: Vous pouvez migrer une instance existante de l’utilitaire d’administration Deploy vers une nouvelle machine virtuelle à l’aide de l’interface de ligne de commande. 
---
= Migrer une instance ONTAP Select Deploy vers une nouvelle machine virtuelle
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez migrer une instance existante de l’utilitaire d’administration Deploy vers une nouvelle machine virtuelle à l’aide de l’interface de ligne de commande.

Cette procédure consiste à créer une nouvelle machine virtuelle utilisant les données de configuration de la machine virtuelle d'origine. Les machines virtuelles nouvelle et d'origine doivent exécuter la même version de l'utilitaire Deploy. Vous ne pouvez pas migrer vers une version différente de l'utilitaire Deploy.



== Étape 1 : Sauvegarder les données de configuration du déploiement

Vous devez créer une sauvegarde des données de configuration de déploiement lors de la migration de la machine virtuelle. Vous devez également créer une sauvegarde après le déploiement d'un cluster ONTAP Select . Les données sont enregistrées dans un fichier chiffré unique que vous pouvez télécharger sur votre poste de travail local.

.Avant de commencer
* Assurez-vous que Deploy n’exécute aucune autre tâche pendant l’opération de sauvegarde.
* Enregistrez l’image de la machine virtuelle de déploiement d’origine.
+

CAUTION: L'image de machine virtuelle de déploiement d'origine est requise plus tard dans cette procédure lorsque vous restaurez les données de configuration de déploiement de l'original vers la nouvelle machine virtuelle.



.À propos de cette tâche
Le fichier de sauvegarde que vous créez capture toutes les données de configuration de la machine virtuelle. Ces données décrivent les aspects de votre environnement de déploiement, y compris les clusters ONTAP Select .

.Étapes
. Sign in à l’interface de ligne de commande de l’utilitaire de déploiement à l’aide de SSH avec le compte administrateur.
. Créez une sauvegarde des données de configuration de déploiement, qui sont stockées dans un répertoire interne sur le serveur de déploiement :
+
[source, cli]
----
deploy backup create
----
. Fournissez un mot de passe pour la sauvegarde lorsque vous y êtes invité.
+
Le fichier de sauvegarde est crypté en fonction du mot de passe.

. Afficher les sauvegardes disponibles dans le système :
+
[source, cli]
----
deploy backup show -detailed
----
. Sélectionnez votre fichier de sauvegarde en fonction de la date dans le champ *Créé* et enregistrez la valeur *URL de téléchargement*.
+
Vous pouvez accéder au fichier de sauvegarde via l'URL.

. À l’aide d’un navigateur Web ou d’un utilitaire tel que Curl, téléchargez le fichier de sauvegarde sur votre poste de travail local avec l’URL.




== Étape 2 : Installez une nouvelle instance de la machine virtuelle Deploy

Vous devez créer une nouvelle instance de la machine virtuelle Deploy que vous pouvez mettre à jour avec les données de configuration de la machine virtuelle d'origine.

.Avant de commencer
Vous devez être familiarisé avec les procédures utilisées pour télécharger et déployer la machine virtuelle ONTAP Select Deploy dans un environnement VMware.

.À propos de cette tâche
Cette tâche est décrite à un niveau élevé.

.Étapes
. Créez une nouvelle instance de la machine virtuelle Deploy :
+
.. Téléchargez l'image de la machine virtuelle.
.. Déployez la machine virtuelle et configurez l’interface réseau.
.. Accédez à l’utilitaire de déploiement à l’aide de SSH.




.Informations connexes
link:task_install_deploy.html["Installer ONTAP Select Deploy"]



== Étape 3 : Restaurez les données de configuration de déploiement sur la nouvelle machine virtuelle

Vous devez restaurer les données de configuration de la machine virtuelle d'origine de l'utilitaire Deploy vers la nouvelle machine virtuelle. Ces données se trouvent dans un fichier unique que vous devez télécharger depuis votre poste de travail local.

.Avant de commencer
Vous devez disposer des données de configuration d'une sauvegarde précédente. Ces données sont contenues dans un fichier unique et doivent être disponibles sur votre poste de travail local.

.Étapes
. Dans une invite de commandes sur votre poste de travail local, utilisez l'utilitaire sftp pour transférer le fichier de sauvegarde vers la machine virtuelle Deploy, comme indiqué dans l'exemple suivant :
+
....
sftp admin@10.234.81.101 (provide password when prompted)
put deploy_backup_20190601162151.tar.gz
exit
....
. Sign in à l’interface de ligne de commande de l’utilitaire de déploiement à l’aide de SSH avec le compte administrateur.
. Restaurez les données de configuration :
+
[source, cli]
----
deploy backup restore -path <path_name> -filename <file_name>
----
+
Exemple de commande

+
`deploy backup restore -path /home/admin -filename deploy_backup_20180601162151.tar.gz`


